### ISSUE TITLE
Regression: Locale deployment is broken

### ISSUE THREAD

**Issue by straight-shoota** [mamantoha/humanize_time#12]
With version 0.7.0 a binary using `humanize_time` could be deployed to a different machine without requiring any dependencies on the target machine.
When I upgraded shardbox.org to 0.9.0 all translations for i18n were missing.

I didn't investigate further, but the migration from `TechMagister/i18n.cr` to `crystal-i18n/i18n` (#10) is an obvious cause. The old library embedded the localization files into the binary, whereas the integration with the new library just registers the paths and loads them at runtime. This obviously requires the localization files to be available and at the same location as in the build environment. That's a huge restriction for easy deployment workflow.

I'm filing this here instead of a feature request to `crystal-i18n/i18n` because I don't use i18n, I'm just using `humanize_time`. This shard used to work without requiring runtime dependencies, now it doesn't anymore.
I see a couple of options:

* Add embeddable localizations as feature to `crystal-i18n/i18n`
* Add embedded localization for this shard (`en` only would be sufficient)
* Declare that it's not a supported feature, but offer a way to roll your own. There should be an option to disable loading build paths at runtime.

**Comment by mamantoha** [comment]
Hi @straight-shoota
 
> Add embeddable localizations as feature to `crystal-i18n/i18n`

I think it's the best option.

**Comment by ellmetha** [comment]
I came across this issue by chance and I ended up creating crystal-i18n/i18n#4. I will have a look at it in the next few days!
